language: java
jdk:
  - openjdk17
branches:
  only:
    - main

# Travis CI Server's Home
# 해당 디렉토리에서 캐시하여, 같은 의종성은 다음 배포때부터 다시 받지않도록 설정
cache:
  - directories:
      - '$HOME/.m2/repository'
      - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료 시 설정한 메일로 알람
notifications:
  email:
    recipients:
      - dbal5886@gmail.com
# gradlew 실행 권한 설정
before_install:
  - chmod +x gradlew
