server:
  port: '8089'
spring:
  jpa:
    properties:
      hibernate:
        ddl-auto: create-drop
        show_sql: true
        format_sql: true
    database:
      platform: org.hibernate.dialect.MySQL8Dialect
  output:
    ansi:
      enabled: always
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
